

# actuadores
POST http://localhost:3000/api/actuadores HTTP/1.1
Content-Type: application/json

{
    
  "componente_id": "PUERTA",
  "valor": true,
  "tipo": "actuador",
  "puerta": 3
  
}

### movimientos 

POST http://localhost:3000/api/postMovimiento HTTP/1.1
Content-Type: application/json

{
    
      "username": "Test1",
      "email":"Test1@gmail.com",
      "rfid": "111-111-111",
      "puerta": 2
  
}
#### usuarios
POST http://localhost:3000/api/register HTTP/1.1
Content-Type: application/json

{
    
      "username": "Test5",
      "email":"Test5@gmail.com",
      "rfid": "555-555-555",
      "puerta": 2
  
}

### puertas 

POST http://localhost:3000/api/puertas HTTP/1.1
Content-Type: application/json

{
    
      "numero": 3,
      "status":false,
      "acceso": false,
      "alarma": false,
      "activacion": "local"
  
}




### GET DE TODOS LOS COMPONENTES
GET  http://localhost:3000/api/actuadores HTTP/1.1

### GET DE UN COMPONENTE EN ESPECIFICO CON SU ID
GET  http://localhost:3000/api/actuadores/660357cd0857750eec6c4113 HTTP/1.1

### ACTUALIZAR UN COMPONENTE CON SU ID
PUT http://localhost:3000/api/actuadores/65ff85d16bebdfad691d7b9e HTTP/1.1

### ACTUALIZAR UN COMOPONENTE 
PATCH   http://localhost:3000/api/actuadores/65f88ab4acc47d14279c0980 HTTP/1.1

### ELIMINAR UN COMPONENTE
DELETE http://localhost:3000/api/actuadores/65f51798d8c4c8fc00d7d716 HTTP/1.1



# PUERTAS 
###

PUT http://localhost:3000/api/puertas/66084d807f5c2b9b20c7aa9c HTTP/1.1