
POST http://localhost:3000/api/actuadores HTTP/1.1
Content-Type: application/json

{
    
  "componente_id": "SERVO-MOTOR",
  "valor": true,
  "tipo": "actuador"
  
}


### GET DE TODOS LOS COMPONENTES
GET  http://localhost:3000/api/actuadores HTTP/1.1

### GET DE UN COMPONENTE EN ESPECIFICO CON SU ID
GET  http://localhost:3000/api/actuadores/65f88ab4acc47d14279c0980 HTTP/1.1

### ACTUALIZAR UN COMPONENTE CON SU ID
PUT http://localhost:3000/api/actuadores/65ff85d16bebdfad691d7b9e HTTP/1.1

### ACTUALIZAR UN COMOPONENTE 
PATCH   http://localhost:3000/api/actuadores/65f88ab4acc47d14279c0980 HTTP/1.1

### ELIMINAR UN COMPONENTE
DELETE http://localhost:3000/api/actuadores/65f51798d8c4c8fc00d7d716 HTTP/1.1