

# actuadores
POST http://localhost:3000/api/actuadores HTTP/1.1
Content-Type: application/json

{
    
  "componente_id": "PUERTA",
  "valor": true,
  "tipo": "actuador",
  "puerta": 3
  
}

### movimientos 

POST http://localhost:3000/api/postMovimiento HTTP/1.1
Content-Type: application/json

{
    
      "username": "Test4",
      "email":"Test4@gmail.com",
      "emailAdmin": "Admin2@gmail.com",
      "rfid": "444-444-444",
      "puerta": 1
  
}
#### usuarios
POST http://localhost:3000/api/register HTTP/1.1
Content-Type: application/json

{
    
      "username": "Test4",
      "email":"Test4@gmail.com",
      "emailAdmin": "Admin2@gmail.com",
      "rfid": "444-444-444",
      "puerta": 2
  
}

### puertas 

POST http://localhost:3000/api/puertas HTTP/1.1
Content-Type: application/json

{
    
      "numero": 3,
      "idPuerta": 333,
      "status":false,
      "acceso": false,
      "alarma": false,
      "activacion": "local"
  
}
### 

POST http://localhost:3000/api/puertasForm HTTP/1.1
Content-Type: application/json

{
    
      "numero": 1,
      "emailAdmin" :"Admin@gmail.com",
      "idPuerta": 212124
     
  
}

PUT  http://localhost:3000/api/actualizarUsuario HTTP/1.1
Content-Type: application/json

{
    
      "email":"Test10", 
      ""
     
  
}




### GET DE TODOS LOS COMPONENTES
GET  http://localhost:3000/api/actuadores HTTP/1.1

### GET DE UN COMPONENTE EN ESPECIFICO CON SU ID
GET  http://localhost:3000/api/actuadores/660357cd0857750eec6c4113 HTTP/1.1

### ACTUALIZAR UN COMPONENTE CON SU ID
PUT http://localhost:3000/api/actuadores/65ff85d16bebdfad691d7b9e HTTP/1.1

### ACTUALIZAR UN COMOPONENTE 
PATCH   http://localhost:3000/api/actuadores/65f88ab4acc47d14279c0980 HTTP/1.1

### ELIMINAR UN COMPONENTE
DELETE http://localhost:3000/api/actuadores/65f51798d8c4c8fc00d7d716 HTTP/1.1



# PUERTAS 
### actualizar puerta 
PUT http://localhost:3000/api/puertas/66084d807f5c2b9b20c7aa9c HTTP/1.1

### get de todas las puertas 

GET  http://localhost:3000/api/puertas HTTP/1.1
###

GET  http://localhost:3000/api/puertaNumero HTTP/1.1

### get de puerta con su numero de puerta 


DELETE http://localhost:3000/api/borrarUsuario/Test5@test.com 

###
POST https://react-iot-application.onrender.com/api/login 
Content-Type: application/json

{
    
      "email":"Admin@gmail.com", 
      "password": "Admin"
     
  
}